/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

// PRINT LIABARIES
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Hospital extends javax.swing.JFrame {
private JFrame frame;
    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jtxtPrescription = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jtxtRef = new javax.swing.JTextField();
        jTextIsue = new javax.swing.JTextField();
        jTxtTab = new javax.swing.JTextField();
        jTextExp = new javax.swing.JTextField();
        jTextSEffect = new javax.swing.JTextField();
        jTextdose = new javax.swing.JTextField();
        jTextStorage = new javax.swing.JTextField();
        jTextFurtherInfo = new javax.swing.JTextField();
        jTextUse = new javax.swing.JTextField();
        jTextUsage = new javax.swing.JTextField();
        jTextPtID = new javax.swing.JTextField();
        jTextptadd = new javax.swing.JTextField();
        jTextDOB = new javax.swing.JTextField();
        jTextPtName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Doctor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Apointment");

        jButton5.setText("Patient");

        jButton6.setText("Reset");

        jtxtPrescription.setText("Prescription");
        jtxtPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrescriptionActionPerformed(evt);
            }
        });

        jButton8.setText("Login");

        jButton10.setText("Print");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Exit");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtPrescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jtxtPrescription)
                    .addComponent(jButton8)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1050, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setText("Hospital Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 80));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 450, 330));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient prescription");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 600, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setText("Hospital Management System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Reference No. :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Panadol by GSK", "abc", "Brufen", "Amoxil", "xyz" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Name of Tablets:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Number of Tab:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Doze mg:");
        jLabel7.setToolTipText("Dose");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Exp Date:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Issue Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Posible side effect:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 130, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Daily Doze:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 130, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Storage Advice:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Further info:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Medicine uses:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Usage:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Date of Birth:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("patient id:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("patient address:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("patient Name:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jtxtDose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 160, -1));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, -1));

        jTextIsue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextIsue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 160, -1));

        jTxtTab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTxtTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 160, -1));

        jTextExp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, -1));

        jTextSEffect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextSEffect, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 160, -1));

        jTextdose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextdose, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 160, -1));

        jTextStorage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 160, -1));

        jTextFurtherInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextFurtherInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 160, -1));

        jTextUse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 160, -1));

        jTextUsage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextUsage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 160, -1));

        jTextPtID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextPtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 160, -1));

        jTextptadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextptadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 160, -1));

        jTextDOB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 160, -1));

        jTextPtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextPtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 160, -1));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tab", "Reference NO", "Doze mg", "Number of Tab", "Issue Date", "Exp Date", "Daily Doze", "Posible Side Efects", "Further Info", "Storage Advice", "Usage ", "medicine Usage", "Patient id", "DOB ", "Patient Name", "Patient address"
            }
        ));
        jScrollPane2.setViewportView(jtable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1050, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
frame = new JFrame ();  //Exit line code
if (JOptionPane.showConfirmDialog(frame,"Conform if you wnat to exit", "Hospital Management System",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
    System.exit(0);
}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // PRINT code here:
        try{
            jTextArea1.print();
        } catch(PrinterException ex){
            Logger.getLogger(Hospital.class.getName()).log (Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // DROP DOWN MENUE code here:
        if (jComboBox1.getSelectedItem().equals("Panadol by GSK"))
        {
            jtxtRef.setText("Pan123");
            jtxtDose.setText("2");
            jTxtTab.setText("12");
            jTextIsue.setText("19-12-2018");
            jTextExp.setText("10-12-2019");
            jTextdose.setText("3");
            jTextSEffect.setText("Headhack");
            
            jTextFurtherInfo.setText("Place Despancry");
            jTextStorage.setText("Room Temp");
            jTextUsage.setText("Pain in Head");
            jTextUse.setText("with water");
            jTextPtID.setText("P1712197");
            jTextDOB.setText("27-JUNE-1997");
            jTextPtName.setText("");
            jTextptadd.setText("");
        }
        
         if (jComboBox1.getSelectedItem().equals("abc"))
        {
            jtxtRef.setText("Pan123");
            jtxtDose.setText("2");
            jTxtTab.setText("12");
            jTextIsue.setText("19-12-2018");
            jTextExp.setText("10-12-2019");
            jTextdose.setText("3");
            jTextSEffect.setText("Headhack");
            
            jTextFurtherInfo.setText("Place Despancry");
            jTextStorage.setText("Room Temp");
            jTextUsage.setText("Pain in Head");
            jTextUse.setText("with water");
            jTextPtID.setText("P1712197");
            jTextDOB.setText("27-JUNE-1997");
            jTextPtName.setText("");
            jTextptadd.setText("");
        }
        else if (jComboBox1.getSelectedItem().equals("abc"))
        {
            jtxtRef.setText("abc123");
            jtxtDose.setText("3");
            jTxtTab.setText("12");
            jTextIsue.setText("29-12-2018");
            jTextExp.setText("20-12-2019");
            jTextdose.setText("4");
            jTextSEffect.setText("Fever");
            
            jTextFurtherInfo.setText("Place Despancry");
            jTextStorage.setText("Room Temp");
            jTextUsage.setText("Head heating");
            jTextUse.setText("with milk");
            jTextPtID.setText("P1712198");
            jTextDOB.setText("27-JUNE-1997");
            jTextPtName.setText("");
            jTextptadd.setText("");
        }
        else if (jComboBox1.getSelectedItem().equals("xyz"))
        {
            jtxtRef.setText("brf123");
            jtxtDose.setText("3");
            jTxtTab.setText("6");
            jTextIsue.setText("25-12-2018");
            jTextExp.setText("30-12-2019");
            jTextdose.setText("6");
            jTextSEffect.setText("Bledding");
            
            jTextFurtherInfo.setText("Place Despancry");
            jTextStorage.setText("below 20 degree");
            jTextUsage.setText("Blooding");
            jTextUse.setText("with milk");
            jTextPtID.setText("br1712198");
            jTextDOB.setText("27-JUNE-1997");
            jTextPtName.setText("");
            jTextptadd.setText("");
        }
        else if (jComboBox1.getSelectedItem().equals("Amoxil"))
        {
            jtxtRef.setText("amx123");
            jtxtDose.setText("2");
            jTxtTab.setText("4");
            jTextIsue.setText("05-12-2018");
            jTextExp.setText("01-12-2019");
            jTextdose.setText("03");
            jTextSEffect.setText("Corns");
            
            jTextFurtherInfo.setText("Place Despancry");
            jTextStorage.setText("below 15 degree");
            jTextUsage.setText("red spot coming out");
            jTextUse.setText("with water");
            jTextPtID.setText("amx1712198");
            jTextDOB.setText("27-JUNE-1997");
            jTextPtName.setText("");
            jTextptadd.setText("");
        }
        else if (jComboBox1.getSelectedItem().equals("Make a Selection"))
        {
            jtxtRef.setText("");
            jtxtDose.setText("");
            jTxtTab.setText("");
            jTextIsue.setText("");
            jTextExp.setText("");
            jTextdose.setText("");
            jTextSEffect.setText("");            
           jTextFurtherInfo.setText("");
            jTextStorage.setText("");
            jTextUsage.setText("");
            jTextUse.setText("");
            jTextPtID.setText("");
            jTextDOB.setText("");
            jTextPtName.setText("");
            jTextptadd.setText("");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jtxtPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrescriptionActionPerformed
        // prescription code here:
        String Qty1 = (jtxtRef.getText());
        String Qty2 = (jtxtDose.getText());
        String Qty3 = (jTxtTab.getText());
        String Qty4 = (jTextIsue.getText());
        String Qty5 = (jTextPtID.getText());
        String Qty6 = (jTextdose.getText());
        String Qty7 = (jTextSEffect.getText());
        String Qty8 = (jTextFurtherInfo.getText());
        String Qty9 = (jTextStorage.getText());
        String Qty10 = (jTextPtName.getText());
        String Qty11 = (jTextDOB.getText());
        String Qty12 = (jTextptadd.getText());
        String Qty13 = ("");
        
        jTextArea1.setText("");
        jTextArea1.append("\t\n\tHospital Mangement System\n"
        +"\nPatient Name:\t\t" + Qty10
        +"\nDate of Birth:\t\t" + Qty11
        +"\nPatient Address:\t" + Qty12
        +"\nPrescription no:\t\t" + Qty1
        +"\nDose (mg):\t\t" + Qty2
        +"\nNumber of Tablets:\t" + Qty3  
       +"\nIssue:\t\t" + Qty4
        +"\nDaily Dose:\t\t" + Qty6
        +"\nSide Efect:\t\t" + Qty7
        +"\nInformation (mg):\t" + Qty8
        +"\nMedicatio (mg):\t\t" + Qty9 
        +"\nPatient Id\t\t" + Qty5 
        +"\n\n\tPatient Instruction we have introduce a \n\t free text confirmation\n\t" 
                +"Text Reminder For Apointment");
    }//GEN-LAST:event_jtxtPrescriptionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) jtable.getModel();
        model.addRow(new Object[]{jComboBox1.getSelectedItem().toString(),
        jtxtRef.getText(),jtxtDose.getText(),jTxtTab.getText(),jTextIsue.getText(),
        jTextExp.getText(),jTextdose.getText(),jTextSEffect.getText(),jTextFurtherInfo.getText(),
        jTextStorage.getText(),jTextUsage.getText(),jTextUse.getText(),jTextPtID.getText(),
        jTextDOB.getText(),jTextPtName.getText(),jTextptadd.getText()});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // DELETE code IS here:
        DefaultTableModel model= (DefaultTableModel) jtable.getModel();
       if (jtable.getSelectedRow() ==-1);{
         if (jtable.getRowCount()==0);{
           
           JOptionPane.showMessageDialog(null,"SELECTed ROW will be DELETE","Hospital Mangement System",
           JOptionPane.OK_OPTION);
      
         }/*
          JOptionPane.showMessageDialog(null,"SELECT ROW TO DELETE","Hospital Mangement System",
                        JOptionPane.OK_OPTION);
                 
                       }
            }else{*/
            model.removeRow(jtable.getSelectedRow());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextDOB;
    private javax.swing.JTextField jTextExp;
    private javax.swing.JTextField jTextFurtherInfo;
    private javax.swing.JTextField jTextIsue;
    private javax.swing.JTextField jTextPtID;
    private javax.swing.JTextField jTextPtName;
    private javax.swing.JTextField jTextSEffect;
    private javax.swing.JTextField jTextStorage;
    private javax.swing.JTextField jTextUsage;
    private javax.swing.JTextField jTextUse;
    private javax.swing.JTextField jTextdose;
    private javax.swing.JTextField jTextptadd;
    private javax.swing.JTextField jTxtTab;
    private javax.swing.JTable jtable;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JButton jtxtPrescription;
    private javax.swing.JTextField jtxtRef;
    // End of variables declaration//GEN-END:variables
}
